# Generated by Django 4.1.4 on 2023-03-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=13, null=True)),
                ('link_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('link_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('link_saf_google', models.CharField(blank=True, max_length=255, null=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='website/upload/%Y/%m/%d/')),
                ('color', models.CharField(max_length=10, null=True)),
                ('carousel1', models.ImageField(blank=True, null=True, upload_to='website/upload/%Y/%m/%d/')),
                ('carousel2', models.ImageField(blank=True, null=True, upload_to='website/upload/%Y/%m/%d/')),
                ('carousel3', models.ImageField(blank=True, null=True, upload_to='website/upload/%Y/%m/%d/')),
            ],
        ),
    ]
